# Generated by Django 5.1 on 2024-08-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='dtEntrada',
            field=models.DateField(auto_now_add=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='dtSaida',
            field=models.DateField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='nomeCliente',
            field=models.CharField(max_length=150, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='placaVeiculo',
            field=models.CharField(max_length=7, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='tipoVeiculo',
            field=models.CharField(max_length=150, verbose_name='Tipo do Veículo'),
        ),
    ]
