# Generated by Django 5.1 on 2024-08-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_estacionamento_dtentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='dtEntrada',
            field=models.TimeField(auto_now_add=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='dtSaida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
    ]
