# Generated by Django 5.1 on 2024-08-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_estacionamento_dtentrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamento',
            old_name='dtEntrada',
            new_name='hrEntrada',
        ),
        migrations.RenameField(
            model_name='estacionamento',
            old_name='dtSaida',
            new_name='hrSaida',
        ),
    ]
