# Generated by Django 5.1 on 2024-08-24 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_estacionamento_hrentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='hrEntrada',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Horário de Entrada'),
        ),
    ]
