# Generated by Django 5.1 on 2024-08-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_estacionamento_hrentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='hrEntrada',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='hrSaida',
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='dtEntrada',
            field=models.DateField(auto_now_add=True, default='2024-08-24 12:00:00', verbose_name='Data de Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='dtSaida',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
    ]
