# Generated by Django 5.1 on 2024-08-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_remove_estacionamento_hrentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='dtEntrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
