# Generated by Django 5.1 on 2024-08-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_alter_estacionamento_dtentrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='dtEntrada',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='dtSaida',
        ),
    ]
