# Generated by Django 5.1 on 2024-08-24 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_remove_estacionamento_dtentrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='dtEntrada',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='dtSaida',
            field=models.TimeField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
    ]
